name: kopia-restore

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to restore from"
        type: choice
        required: true
        options: [alpha, staging]
      restore_prefix:
        description: "Path inside snapshot to restore (e.g., a/b/c or file.ext)"
        required: true
      snapshot_id:
        description: "Specific snapshot ID (leave empty for latest)"
        required: false
        default: ""
      restore_mode:
        description: "Where to put the restored files"
        type: choice
        required: true
        options: [preview, inplace]
        default: preview

jobs:
  restore:
    runs-on: container-builder

    steps:
      - name: Select environment
        id: sel
        run: |
          case "${{ github.event.inputs.env }}" in
            alpha)
              echo "REPO_BUCKET=edream-storage-dreams-alpha-backup" >> "$GITHUB_OUTPUT"
              echo "DST_BUCKET=edream-storage-dreams-alpha" >> "$GITHUB_OUTPUT"
              echo "R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}" >> "$GITHUB_OUTPUT"
              echo "KOPIA_PASSWORD=${{ secrets.KOPIA_PASSWORD_ALPHA }}" >> "$GITHUB_OUTPUT"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.R2_REPO_ACCESS_KEY_ALPHA }}" >> "$GITHUB_OUTPUT"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.R2_REPO_SECRET_KEY_ALPHA }}" >> "$GITHUB_OUTPUT"
              # you said these have full access; keeping names
              echo "DST_KEY=${{ secrets.R2_SRC_READ_KEY_ALPHA }}" >> "$GITHUB_OUTPUT"
              echo "DST_SECRET=${{ secrets.R2_SRC_READ_SECRET_ALPHA }}" >> "$GITHUB_OUTPUT"
              echo "SNAP_ROOT=/mnt/r2alpha" >> "$GITHUB_OUTPUT"
              ;;
            staging)
              echo "REPO_BUCKET=edream-storage-dreams-staging-backup" >> "$GITHUB_OUTPUT"
              echo "DST_BUCKET=edream-storage-dreams-staging" >> "$GITHUB_OUTPUT"
              echo "R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}" >> "$GITHUB_OUTPUT"
              echo "KOPIA_PASSWORD=${{ secrets.KOPIA_PASSWORD_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.R2_REPO_ACCESS_KEY_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.R2_REPO_SECRET_KEY_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "DST_KEY=${{ secrets.R2_SRC_READ_KEY_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "DST_SECRET=${{ secrets.R2_SRC_READ_SECRET_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "SNAP_ROOT=/mnt/r2staging" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Install rclone
        run: curl -fsSL https://rclone.org/install.sh | sudo bash

      - name: Install Kopia
        run: |
          sudo apt-get update && sudo apt-get install -y fuse3 jq
          curl -fsSL https://kopia.io/signing-key | sudo gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kopia-keyring.gpg] https://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
          sudo apt-get update && sudo apt-get install -y kopia
          kopia --version

      - name: Configure rclone (destination)
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [dst]
          type = s3
          provider = Cloudflare
          access_key_id = ${{ steps.sel.outputs.DST_KEY }}
          secret_access_key = ${{ steps.sel.outputs.DST_SECRET }}
          endpoint = https://${{ steps.sel.outputs.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          EOF

      - name: Connect Kopia repo
        env:
          KOPIA_PASSWORD: ${{ steps.sel.outputs.KOPIA_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ steps.sel.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.sel.outputs.AWS_SECRET_ACCESS_KEY }}
        run: |
          kopia repository connect s3 \
            --bucket=${{ steps.sel.outputs.REPO_BUCKET }} \
            --endpoint=${{ steps.sel.outputs.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --region=auto

      - name: Determine snapshot ID
        id: snap
        run: |
          set -euo pipefail
          SNAP_IN="${{ github.event.inputs.snapshot_id }}"
          if [ -n "$SNAP_IN" ]; then
            SNAP="$SNAP_IN"
            echo "Using provided snapshot: $SNAP"
          else
            echo "Fetching latest snapshot ID..."
            SNAP="$(kopia snapshot list --json | jq -r '.[0].id')"
            if [ -z "$SNAP" ] || [ "$SNAP" = "null" ]; then
              echo "ERROR: No snapshots found"; exit 1
            fi
            echo "Using snapshot: $SNAP"
          fi
          echo "snap=$SNAP" >> "$GITHUB_OUTPUT"

      - name: Restore selected prefix to temp (robust for S3/R2)
        run: |
          set -e
          mkdir -p /tmp/restore-root

          RP="${{ github.event.inputs.restore_prefix }}"
          SNAP_ROOT="${{ steps.sel.outputs.SNAP_ROOT }}"
          SNAP_ID="${{ steps.snap.outputs.snap }}"

          echo "Requested restore_prefix: $RP"

          if [ "${RP%/}" != "$RP" ]; then
            # FOLDER -> restore that folder
            SRC_INSIDE="${SNAP_ROOT}/${RP%/}"
            DEST_DIR="/tmp/restore-root/${RP%/}"
            echo "Folder restore: $SRC_INSIDE -> $DEST_DIR"
            mkdir -p "$DEST_DIR"
            kopia snapshot restore "$SNAP_ID" "$SRC_INSIDE" "$DEST_DIR"
            echo "RESTORE_KIND=dir" >> "$GITHUB_ENV"
            echo "RESTORED_DIR=$DEST_DIR" >> "$GITHUB_ENV"
          else
            # FILE -> restore parent folder, we will copy only the file later
            PARENT="$(dirname "$RP")"
            SRC_PARENT="${SNAP_ROOT}/${PARENT%/}"
            DEST_PARENT="/tmp/restore-root/${PARENT%/}"
            echo "File restore (parent-first): $SRC_PARENT -> $DEST_PARENT"
            mkdir -p "$DEST_PARENT"
            kopia snapshot restore "$SNAP_ID" "$SRC_PARENT" "$DEST_PARENT"
            echo "RESTORE_KIND=file" >> "$GITHUB_ENV"
            echo "RESTORED_PARENT=$DEST_PARENT" >> "$GITHUB_ENV"
            echo "RESTORE_FILE=$(basename "$RP")" >> "$GITHUB_ENV"
            echo "RESTORE_PREFIX_PARENT=$PARENT" >> "$GITHUB_ENV"
          fi

          echo "Restore completed under /tmp/restore-root"

      - name: Copy restored files to destination (preview or inplace)
        run: |
          set -e
          MODE="${{ github.event.inputs.restore_mode }}"
          RP="${{ github.event.inputs.restore_prefix }}"

          if [ "$MODE" = "preview" ]; then
            TS=$(date -u +%Y-%m-%dT%H%M%SZ)
            DEST_BASE="dst:${{ steps.sel.outputs.DST_BUCKET }}/restores/${TS}"
          else
            DEST_BASE="dst:${{ steps.sel.outputs.DST_BUCKET }}"
          fi

          if [ "${RESTORE_KIND}" = "dir" ]; then
            SRC_DIR="${RESTORED_DIR%/}/"
            DEST_DIR="${DEST_BASE}/${RP%/}/"
            echo "Copy folder: $SRC_DIR -> $DEST_DIR"
            rclone copy "$SRC_DIR" "$DEST_DIR" --checkers=64 --transfers=32 --progress
          else
            BASENAME="$RESTORE_FILE"
            PARENT="${RESTORE_PREFIX_PARENT}"
            SRC_DIR="${RESTORED_PARENT%/}/"
            DEST_DIR="${DEST_BASE}/$(dirname "$RP")/"
            echo "Copy file: $SRC_DIR$BASENAME -> $DEST_DIR"
            rclone copy "$SRC_DIR" "$DEST_DIR" \
              --include "$BASENAME" \
              --checkers=64 --transfers=32 --progress
          fi
