name: kopia-list-snapshots

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Which environment?"
        type: choice
        required: true
        options:
          - alpha
          - staging
      limit:
        description: "How many entries to show (default 50)"
        required: false
        default: "50"

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: Select env variables
        id: sel
        run: |
          case "${{ github.event.inputs.env }}" in
            alpha)
              echo "REPO_BUCKET=edream-storage-dreams-alpha-backup" >> "$GITHUB_OUTPUT"
              echo "R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}" >> "$GITHUB_OUTPUT"
              echo "KOPIA_PASSWORD=${{ secrets.KOPIA_PASSWORD_ALPHA }}" >> "$GITHUB_OUTPUT"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.R2_REPO_ACCESS_KEY_ALPHA }}" >> "$GITHUB_OUTPUT"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.R2_REPO_SECRET_KEY_ALPHA }}" >> "$GITHUB_OUTPUT"
              ;;
            staging)
              echo "REPO_BUCKET=edream-storage-dreams-staging-backup" >> "$GITHUB_OUTPUT"
              echo "R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}" >> "$GITHUB_OUTPUT"
              echo "KOPIA_PASSWORD=${{ secrets.KOPIA_PASSWORD_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.R2_REPO_ACCESS_KEY_STAGING }}" >> "$GITHUB_OUTPUT"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.R2_REPO_SECRET_KEY_STAGING }}" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Install Kopia and jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          curl -fsSL https://kopia.io/signing-key | sudo gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kopia-keyring.gpg] https://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
          sudo apt-get update && sudo apt-get install -y kopia
          kopia --version

      - name: Connect to Kopia repo
        env:
          KOPIA_PASSWORD: ${{ steps.sel.outputs.KOPIA_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ steps.sel.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.sel.outputs.AWS_SECRET_ACCESS_KEY }}
        run: |
          kopia repository connect s3 \
            --bucket=${{ steps.sel.outputs.REPO_BUCKET }} \
            --endpoint=${{ steps.sel.outputs.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            --region=auto

      - name: List latest snapshots (ID, source, time)
        run: |
          LIMIT="${{ github.event.inputs.limit }}"
          kopia snapshot list --json | \
            jq -r 'sort_by(.startTime) | reverse | .[] | "\(.id)  \(.source.path)  \(.startTime)"' | \
            head -n "${LIMIT}"
