name: kopia-r2-incremental-alpha

on:
  schedule:
    - cron: "0 6 * * *" # daily 02:00 UTC
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: backup-runner
    env:
      # Destination Kopia repository (R2) – ALPHA
      KOPIA_PASSWORD_ALPHA: ${{ secrets.KOPIA_PASSWORD_ALPHA }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_REPO_ACCESS_KEY_ALPHA }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_REPO_SECRET_KEY_ALPHA }}
      R2_ACCOUNT_ID_ALPHA: ${{ secrets.R2_ACCOUNT_ID }}
      REPO_BUCKET_ALPHA: edream-storage-dreams-alpha-backup

      # Source R2 (read-only) – ALPHA
      RCLONE_SRC_ACCESS_KEY_ID_ALPHA: ${{ secrets.R2_SRC_READ_KEY_ALPHA }}
      RCLONE_SRC_SECRET_ACCESS_KEY_ALPHA: ${{ secrets.R2_SRC_READ_SECRET_ALPHA }}
      SRC_BUCKET_ALPHA: edream-storage-dreams-alpha

    steps:
      - name: Install rclone
        run: curl -fsSL https://rclone.org/install.sh | sudo bash

      - name: Install Kopia
        run: |
          sudo apt-get update && sudo apt-get install -y fuse3
          curl -fsSL https://kopia.io/signing-key | sudo gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kopia-keyring.gpg] https://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
          sudo apt-get update && sudo apt-get install -y kopia
          kopia --version

      - name: Configure rclone (source R2 ALPHA)
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [src-alpha]
          type = s3
          provider = Cloudflare
          access_key_id = ${RCLONE_SRC_ACCESS_KEY_ID_ALPHA}
          secret_access_key = ${RCLONE_SRC_SECRET_ACCESS_KEY_ALPHA}
          endpoint = https://${R2_ACCOUNT_ID_ALPHA}.r2.cloudflarestorage.com
          EOF

      - name: Mount source bucket (read-only, ALPHA)
        run: |
          sudo mkdir -p /mnt/r2src-alpha && sudo chown $USER:$USER /mnt/r2src-alpha
          nohup rclone mount src-alpha:${SRC_BUCKET_ALPHA} /mnt/r2src-alpha \
            --read-only \
            --vfs-cache-mode=full \
            --vfs-cache-max-size=30G \
            --dir-cache-time=6h \
            --poll-interval=0 \
            --transfers=64 --checkers=128 \
            --buffer-size=32M \
            --umask=022 > rclone-mount-alpha.log 2>&1 &
          for i in {1..30}; do mountpoint -q /mnt/r2src-alpha && break || sleep 2; done
          mountpoint -q /mnt/r2src-alpha

      - name: Connect Kopia repository (ALPHA)
        env:
          KOPIA_PASSWORD: ${{ env.KOPIA_PASSWORD_ALPHA }}
        run: |
          kopia repository connect s3 \
            --bucket=${REPO_BUCKET_ALPHA} \
            --endpoint=${R2_ACCOUNT_ID_ALPHA}.r2.cloudflarestorage.com \
            --region=auto

      - name: Create incremental snapshot and maintenance (ALPHA)
        env:
          KOPIA_PASSWORD: ${{ env.KOPIA_PASSWORD_ALPHA }}
        run: |
          export KOPIA_USERNAME=github-actions-alpha
          unset KOPIA_HOSTNAME

          kopia snapshot create /mnt/r2src-alpha --parallel=16

          kopia maintenance run --force

      - name: Unmount (ALPHA)
        if: always()
        run: sudo fusermount3 -u /mnt/r2src-alpha || true
