name: kopia-r2-incremental-staging

on:
  schedule:
    - cron: "0 2 * * *" # daily 02:00 UTC
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: container-builder
    env:
      # Destination Kopia repository (R2) – STAGING
      KOPIA_PASSWORD_STAGING: ${{ secrets.KOPIA_PASSWORD_STAGING }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2_REPO_ACCESS_KEY_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_REPO_SECRET_KEY_STAGING }}
      R2_ACCOUNT_ID_STAGING: ${{ secrets.R2_ACCOUNT_ID }}
      REPO_BUCKET_STAGING: edream-storage-dreams-staging-backup

      # Source R2 (read-only) – STAGING
      RCLONE_SRC_ACCESS_KEY_ID_STAGING: ${{ secrets.R2_SRC_READ_KEY_STAGING }}
      RCLONE_SRC_SECRET_ACCESS_KEY_STAGING: ${{ secrets.R2_SRC_READ_SECRET_STAGING }}
      SRC_BUCKET_STAGING: edream-storage-dreams-staging

    steps:
      - name: Install rclone
        run: curl -fsSL https://rclone.org/install.sh | sudo bash

      - name: Install Kopia
        run: |
          sudo apt-get update && sudo apt-get install -y fuse3
          curl -fsSL https://kopia.io/signing-key | sudo gpg --dearmor -o /usr/share/keyrings/kopia-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kopia-keyring.gpg] https://packages.kopia.io/apt/ stable main" | sudo tee /etc/apt/sources.list.d/kopia.list
          sudo apt-get update && sudo apt-get install -y kopia

      - name: Configure rclone (source R2 STAGING)
        run: |
          mkdir -p ~/.config/rclone
          cat > ~/.config/rclone/rclone.conf <<EOF
          [src-staging]
          type = s3
          provider = Cloudflare
          access_key_id = ${RCLONE_SRC_ACCESS_KEY_ID_STAGING}
          secret_access_key = ${RCLONE_SRC_SECRET_ACCESS_KEY_STAGING}
          endpoint = https://${R2_ACCOUNT_ID_STAGING}.r2.cloudflarestorage.com
          EOF

      - name: Mount source bucket (read-only, STAGING)
        run: |
          sudo mkdir -p /mnt/r2src-staging && sudo chown $USER:$USER /mnt/r2src-staging
          nohup rclone mount src-staging:${SRC_BUCKET_STAGING} /mnt/r2src-staging \
            --read-only \
            --vfs-cache-mode=full \
            --vfs-cache-max-size=20G \
            --dir-cache-time=6h \
            --poll-interval=0 \
            --transfers=16 --checkers=32 \
            --buffer-size=8M \
            --umask=022 > rclone-mount-staging.log 2>&1 &
          for i in {1..30}; do mountpoint -q /mnt/r2src-staging && break || sleep 2; done
          mountpoint -q /mnt/r2src-staging

      - name: Connect Kopia repository (STAGING)
        env:
          KOPIA_PASSWORD: ${{ env.KOPIA_PASSWORD_STAGING }}
        run: |
          kopia repository connect s3 \
            --bucket=${REPO_BUCKET_STAGING} \
            --endpoint=${R2_ACCOUNT_ID_STAGING}.r2.cloudflarestorage.com \
            --region=auto

      - name: Create incremental snapshot and maintenance (STAGING)
        run: |
          kopia snapshot create /mnt/r2src-staging --parallel=8
          kopia maintenance run

      - name: Unmount (STAGING)
        if: always()
        run: sudo fusermount3 -u /mnt/r2src-staging || true
